Train branch
sava-cska/Elderly-pigeons pull request #17
Opened 2020-04-14 18:27 UTC by Yurafobus1

2020-04-15 12:53 UTC, evlinsky requested changes
Главный проблемы, которые хотелось бы решить до первого merge:
1. общий стиль у разных частей.
2. сделать графику в виде класса
3. сделать сеть в виде классов и подключить к основной программе (например, с текстовым интерфейсом, и в главной main выбор: сеть+текст или графика)
4. убрать из PR expat!

Остальные комментарии: можно отложить до следующего PR.

2020-04-15 12:53 UTC, evlinsky commented on Makefile
> +#	g++ $(CXXFLAGS) expat-2.2.9/lib/xmlparse.o expat-2.2.9/lib/xmlrole.o expat-2.2.9/lib/xmltok.o obj/model.o obj/main.o -o model
Кажется, что самостоятельно собирать expat не нужно. Можно поставить libexpat1-dev и им пользоваться.

2020-04-15 12:53 UTC, evlinsky commented on Makefile
> +CXX = g++
На данный момент структур каталогов довольно сложная. Разделение на src/include сейчас избыточно. Я бы сделал, чтобы в каждом каталоге лежали вместе и cpp/h файлы.
Подключать заголовочные файлы можно указывая путь "model/model.h".

2020-04-15 12:53 UTC, evlinsky commented on README.md
> +Для установки библиотеки expatxml надо в папке expat-2.2.9 сделать:
Не уверен, что нужен "самодельный" expat,

2020-04-15 12:53 UTC, evlinsky commented on main.cpp
> +#include "model.h"
Нужно сделать небольшой общий txt файл, который постепенно наполнять правилами написания кода в этом проекте:
1. Обычно удобней, чтобы не было табов, а были только спейсы. У всех код выглядит одинаково. Хорошо бы договориться, сколько спейсов давать на отступ.
2. Заголовочные файлы хорошы бы подключать в определенном порядке. Например, стандартные C, стандартные C++, из библиотек, собственные (или как-то еще).

2020-04-15 12:53 UTC, evlinsky commented on main.cpp
> +        draw_table(rendrer_list, game_state);
С отсупами беда --- про них был коммент выше.

2020-04-15 12:53 UTC, evlinsky commented on main.cpp
> +        draw_table(rendrer_list, game_state);
Хотелось бы, чтобы view стал классом, например, пока нет контроллера, он бы получал game_state в конструкторе.

2020-04-15 12:53 UTC, evlinsky commented on model/ex.xml
> +<Game>
не уверен, что это правильный (valid) XML. я бы поставил xmlint и проверил бы с помощью него. там должен быть один стандартный тэг сверху.

2020-04-15 12:53 UTC, evlinsky commented on model/ex.xml
> +	w.w.w.w.
Это помесь XML и простого текстового файла. Не хотелось  бы, чтобы после xml парсера нужен был еще свой дополнительный парсер из <board>.

2020-04-15 12:53 UTC, evlinsky commented on model/ex.xml
> +	1 4
Это не XML стайл. Числа можно сделать аттрибутами тэга.

2020-04-15 12:53 UTC, evlinsky commented on model/ex.xml
> +<Game_state>
Лучше бы было какие-то правило про имена тэогов: с большой буквы или с маленькой.

2020-04-15 12:53 UTC, evlinsky commented on model/include/model.h
> +class Game
Лучше соблюдать правило --- каждый класс в отдельном файле. Если какой-то класс является небольшим и служебным (явно не этой случай), то можно его сделать вложенным.

2020-04-15 12:53 UTC, evlinsky commented on model/include/model.h
> +	std::pair <int, int> last_move;
Мне кажется, это не очень удачаное решение использовать пару. Дальше он приводит к дефайнам. Проще сделать небольшое структуру, например, struct pos_t с координатами x, y. Код станет короче и понятней. Дефайны не потребуются. make_pair тоже станет не нужен pos_t(1, 2) и все или даже {1, 2}

2020-04-15 12:53 UTC, evlinsky commented on model/include/model.h
> +	Game_state();
Нужно какое-то общее соглашение. Например, в начале все специальные методы: конструктор, деструктор и т.д.. потом остальные методы. Там с классом проще разбираться.

2020-04-15 12:53 UTC, evlinsky commented on model/include/model.h
> +	void move (int player, std::pair <int, int> from, std::pair <int, int> to);
?

2020-04-15 12:53 UTC, evlinsky commented on model/include/model.h
> +	std::vector <std::pair <int, int> > get_list_of_correct_moves(int player, std::pair <int, int> from) const;
?

2020-04-15 12:53 UTC, evlinsky commented on model/include/model.h
> +	void save_to_file(std::ofstream &os) const;
Я бы сделал отдельный класс для чтения и записи и не делал бы его френдом, а передавал бы в соответствующие его методы ссылку на model. Он тогда будет пользоваться только публичным методами модели. При смене внутреннего представления модели загрузку/сохранение не нужно будет переделывать.

2020-04-15 12:53 UTC, evlinsky commented on model/include/model.h
> +private:
Может сделать у Game два поля: state (текущее модель) и history (вектор истории). Во view передавать Game. Ведь после каждого хода в history должен добавляться новый элемент.

2020-04-15 12:53 UTC, evlinsky commented on model/include/model.h
> +	void save_to_file(const std::string &file) const;
Уже писал про вынос в отдельный классс.

2020-04-15 12:53 UTC, evlinsky commented on model/include/model.h
> +public:
Тут не до конца понятно. View должен уметь спрашивать текущую историю: список ходов (ход, кто ходил, номера хода). Как он это сделает?

2020-04-15 12:53 UTC, evlinsky commented on model/new.xml
> +<Game>
Уже писал комментарии к аналогичному файлу:
1. нужны соглашения про имена тэгов (маленькие/большие буквы)
2. Когда нужно дальше парсить содержание тэга это не xml стайл. Лучше вводить аттрибуты тэга или новые тэги. <line>.b.b.b.b</line> -- лучше, парсить самому меньше.

2020-04-15 12:53 UTC, evlinsky commented on model/new.xml
> +	<finish_cell_last_move>
<finish_cell_last_move x = "-1" y = "-1" />

2020-04-15 12:53 UTC, evlinsky commented on model/src/model.cpp
> +#define y second
если убрать pair и сделать сыой класс, то это все уйдет.

2020-04-15 12:53 UTC, evlinsky commented on model/src/model.cpp
> +#define pb push_back
не уверен, что надо затруднять читающему код.
можно лучше взять IDE c автодополнением?

2020-04-15 12:53 UTC, evlinsky commented on model/src/model.cpp
> +	if (who_moves() != player) return;
Не до конца понял логику. Не увидел, например, в check_move аналогичной проверки.
Я бы тут уже кидал game_exception, иначе о таких ошибках мы не узнаем, т.е. кто-то некорректно работает с моделью. Обычно нужно вызвать check_move и только если он дал добро, вызывать move.

2020-04-15 12:53 UTC, evlinsky commented on network/include/Client.hpp
> +#ifndef CHECKERS_NETWORK_INCLUDE_CLIENT_HPP_
Надо договориться  в рамках проекта:
1. h или hpp
2. в гардах: CLIENT_H (просто имя файла) или какое-то более длинное название

2020-04-15 12:53 UTC, evlinsky commented on network/src/client/Client.cpp
> +  sf::TcpSocket socket;
Тут надо переделать в класс. В main оставить вызов методов.

2020-04-15 12:53 UTC, evlinsky commented on network/src/client/Client.cpp
> +        socket.send(packet);
нужна обработка ошибок

2020-04-15 12:53 UTC, evlinsky commented on network/src/client/Client.cpp
> +  sf::Socket::Status status = socket.connect(ipAddress, PORT_NUMBER);
нужна обработка ошибок

2020-04-15 12:53 UTC, evlinsky commented on network/src/client/Client.cpp
> +        socket.send(packet);
нужна обработка ошибок

2020-04-15 12:53 UTC, evlinsky commented on network/src/server/Server.cpp
> +            if (client->receive(packet) == sf::Socket::Done) {
обработка ошибок

2020-04-15 12:53 UTC, evlinsky commented on network/src/server/Server.cpp
> +                other_client->send(packet);
тоже

2020-04-15 12:53 UTC, evlinsky commented on ui/include/draw_smf.hpp
> +#pragma once
Надо договориться в рамках проекта pragma once или гарды

2020-04-15 12:53 UTC, evlinsky commented on ui/include/draw_smf.hpp
> +#include <SFML/Graphics.hpp>
Надо договориться про порядок include

2020-04-15 12:53 UTC, evlinsky commented on ui/include/draw_smf.hpp
> +void draw_background(std::list<sf::RectangleShape>& rendrer_list);
Хочется сделать класс

2020-04-15 12:53 UTC, evlinsky commented on ui/src/draw_smf.cpp
> +#include "draw_smf.hpp"
Надо договориться hpp или h

2020-04-15 12:53 UTC, evlinsky commented on ui/src/draw_smf.cpp
> +
Нужен класс.

2020-04-15 12:53 UTC, evlinsky commented on network/src/client/Client.cpp
> +int main() {
Нужно интегрировать с остальной частью проекта. Например, с текстовой графикой, если все вместе сразу тяжело. В главной main можно сделать ключ командной строки: текстовой интерфейс с сетевой игрой/либо графика.

2020-04-15 14:26 UTC, sava-cska commented on model/ex.xml
> +	w.w.w.w.
Я не понимаю, что такое xml-style. Для меня это текстовый файл с тегами (типа html)

2020-04-15 14:31 UTC, sava-cska commented on model/include/model.h
> +	void save_to_file(std::ofstream &os) const;
Но для этого придётся делать методы, возвращающие каждое поле и устанавливающие значения в них. Кажется, это не особо лучше, чем сделать friend функцию (она всё равно зависит от внутреннего устройства, так как выводит всё его содержимое)

2020-04-15 16:59 UTC, sergeypospelov commented on Makefile
> +CXX = g++
fixed.

2020-04-15 17:00 UTC, sergeypospelov commented on ui/src/draw_smf.cpp
> +#include "draw_smf.hpp"
Договариваемся, что `.hpp`. В прошлом коде исправлено.

2020-04-15 17:02 UTC, sergeypospelov commented on main.cpp
> +#include "model.h"
Исправлены пробелы и фигурные скобочки. Файл в процессе.

2020-04-16 07:19 UTC, sergeypospelov commented on model/model.hpp
> +  int who_moves() const;
Нужно `enum`

2020-04-16 15:13 UTC, sava-cska commented on Makefile
> +#	g++ $(CXXFLAGS) expat-2.2.9/lib/xmlparse.o expat-2.2.9/lib/xmlrole.o expat-2.2.9/lib/xmltok.o obj/model.o obj/main.o -o model
Сделано

2020-04-16 15:14 UTC, sava-cska commented on README.md
> +Для установки библиотеки expatxml надо в папке expat-2.2.9 сделать:
Убрали свой expat

2020-04-16 15:15 UTC, sava-cska commented on model/ex.xml
> +<Game>
Как нужно генерировать xml-файл? Я этого не понимаю. То есть я просто склепал его руками. Или же надо как-то по-другому?

2020-04-16 15:22 UTC, sava-cska commented on model/include/model.h
> +class Game
Сделано

2020-04-16 15:24 UTC, sava-cska commented on model/include/model.h
> +	std::pair <int, int> last_move;
Сделано

2020-04-16 15:24 UTC, sava-cska commented on model/include/model.h
> +	Game_state();
Уточним в файле

2020-04-16 15:24 UTC, sava-cska commented on model/include/model.h
> +	void move (int player, std::pair <int, int> from, std::pair <int, int> to);
Не понял замечания

2020-04-16 15:24 UTC, sava-cska commented on model/include/model.h
> +	std::vector <std::pair <int, int> > get_list_of_correct_moves(int player, std::pair <int, int> from) const;
И здесь тоже не понял

2020-04-16 15:57 UTC, sava-cska commented on model/include/model.h
> +private:
Сделано

2020-04-16 15:58 UTC, sava-cska commented on model/include/model.h
> +public:
Пробегается по всем состояниям (он умеет спрашивать их количество и каждый по отдельности)

2020-04-16 15:58 UTC, sava-cska commented on model/src/model.cpp
> +#define y second
Сделано

2020-04-16 15:58 UTC, sava-cska commented on model/src/model.cpp
> +#define pb push_back
А что не так?

2020-04-16 16:00 UTC, sava-cska commented on model/src/model.cpp
> +	if (who_moves() != player) return;
Я не могу использовать в check_move who_moves, потому что who_moves реализован через check_move

2020-04-16 16:14 UTC, sava-cska commented on model/model.hpp
> +  int who_moves() const;
Сделал

2020-04-23 18:24 UTC, closed without merging