Train branch
sava-cska/Elderly-pigeons pull request #26
Opened 2020-05-05 16:29 UTC by sava-cska

2020-05-09 16:54 UTC, evlinsky requested changes

2020-05-09 16:54 UTC, evlinsky commented on controller/Player.cpp
> +  return network.send_event(new MoveEvent(from, to));
Похоже на memory leak. Здесь точно нужно new? Может достаточно send_event(MouseEvent(from, to))?

2020-05-09 16:54 UTC, evlinsky commented on controller/Player.cpp
> +  network.send_event(new GiveUpEvent());
memory leak?

2020-05-09 16:54 UTC, evlinsky commented on Makefile
>  CXX = g++
Все-таки хочется уметь запускать тесты из главного мейкфайла

2020-05-09 16:54 UTC, evlinsky commented on model/Makefile
> +CFLAGS = -I include -std=c++14 -Wall -Wextra
Хочется запускать тесты из главного мейкфайла, ну и собирать, конечно, тоже

2020-05-09 16:54 UTC, evlinsky commented on tclap/Arg.h
> +// -*- Mode: c++; c-basic-offset: 4; tab-width: 4; -*-
Это точно вкоммичивать не стоит!
sudo apt-get install libtclap-dev

2020-05-09 17:08 UTC, evlinsky requested changes

2020-05-09 17:08 UTC, evlinsky commented on Makefile
> +INC = -Inetwork -Imodel -Iui -Icontroller -Itclap
Это лишнее, мне кажется

2020-05-09 17:08 UTC, evlinsky commented on controller/Event.cpp
> +    e = new controller::MoveEvent(packet);
непонятно, где delete

2020-05-09 17:08 UTC, evlinsky commented on controller/Event.cpp
> +    e = new controller::GiveUpEvent(packet);
непонятно, где delete

2020-05-09 17:14 UTC, evlinsky requested changes

2020-05-09 17:14 UTC, evlinsky commented on model/CompPlayer.cpp
> +#include "CompPlayer.hpp"
Я бы вынес CompPlayer в отдельный каталог (например, ai). Формально он не имеет отношения к модели.

2020-05-09 17:16 UTC, evlinsky requested changes

2020-05-09 17:16 UTC, evlinsky commented on ui/Graphics.cpp
> +void Gra::draw_SafeLoad(std::list<Frame> &render_list, sf::Vector2f lu_point,
вроде везде snake_case: draw_safe_load

2020-05-21 11:07 UTC, sergeypospelov commented on model/CompPlayer.cpp
> +#include "CompPlayer.hpp"
Исправлено

2020-05-21 11:07 UTC, sergeypospelov commented on controller/Event.cpp
> +    e = new controller::GiveUpEvent(packet);
Исправлено

2020-05-21 11:07 UTC, sergeypospelov commented on controller/Event.cpp
> +    e = new controller::MoveEvent(packet);
Исправлено

2020-05-21 11:07 UTC, sergeypospelov commented on Makefile
> +INC = -Inetwork -Imodel -Iui -Icontroller -Itclap
Да, исправлено

2020-05-21 11:07 UTC, sergeypospelov commented on tclap/Arg.h
> +// -*- Mode: c++; c-basic-offset: 4; tab-width: 4; -*-
Удалено

2020-05-21 11:08 UTC, sergeypospelov commented on model/Makefile
> +CFLAGS = -I include -std=c++14 -Wall -Wextra
Сделано, main для тестов -- main_test_model.cpp

2020-05-21 11:08 UTC, sergeypospelov commented on Makefile
>  CXX = g++
Сделано

2020-05-21 11:08 UTC, sergeypospelov commented on controller/Player.cpp
> +  network.send_event(new GiveUpEvent());
Исправлено

2020-05-21 11:08 UTC, sergeypospelov commented on controller/Player.cpp
> +  return network.send_event(new MoveEvent(from, to));
Исправлено

2020-05-23 11:19 UTC, evlinsky approved these changes

2020-05-23 11:19 UTC, evlinsky commented on ai/CompPlayer.cpp
> +int CompPlayer::score(GameState G) const {
Кажется, здесь забыли const GameState&

2020-05-23 11:19 UTC, evlinsky commented on ai/CompPlayer.cpp
> +std::pair<int, Move> CompPlayer::alpha_beta(GameState G, int alpha, int beta,
Здесь тоже внутри метода вроже G не меняется. Зачем копировать?

2020-05-23 11:19 UTC, evlinsky commented on ai/CompPlayer.cpp
> +Move CompPlayer::get_next_move(GameState G, int seconds, int deep) const {
?

2020-05-23 11:19 UTC, evlinsky commented on controller/Player.cpp
> +bool IPlayer::check_move() { return !moves.empty(); }
непонятно, почему пропал const

2020-05-23 11:19 UTC, evlinsky commented on network/Network.cpp
> +    events.push(std::shared_ptr<controller::Event>(controller::unpack(packet)));
Тут не уверен, но может хватит unique_ptr и move. Будет работать быстрее.

2020-05-23 11:19 UTC, evlinsky commented on network/Network.cpp
> +std::queue<std::shared_ptr<controller::Event>> &Network::get_events() { return events; }
а unique не хватит?

2020-05-23 11:19 UTC, evlinsky commented on network/Network.hpp
> +  std::queue<std::shared_ptr<controller::Event>> &get_events();
!

2020-05-23 11:19 UTC, evlinsky commented on ui/Graphics.cpp
> +        }
с мэджик намберами тип а-5 код вообще непонятный.

2020-05-23 11:19 UTC, evlinsky commented on ui/Graphics.cpp
> +          }
тоже магия какая-то

2020-05-23 11:19 UTC, evlinsky commented on ui/Graphics.hpp
> +  std::map<char, sf::Texture *> sprites;
unordered бы лучше подошел.

2020-05-23 11:19 UTC, merged